language: python

services:
  - docker

install:
  - docker build --tag pyneid .

script:
  - docker run --env TRAVIS_JOB_ID=$TRAVIS_JOB_ID pyneid

deploy:
  provider: pypi
  user: __token__
  password: pypi-AgEIcHlwaS5vcmcCJGNhYzhkZTZhLTVlNjMtNGI2Ny05NTA0LWE5NDUyMTkxYWM0YgACN3sicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJweW5laWQiXX0sICJ2ZXJzaW9uIjogMX0AAAYg5t6t2bInccUxVMsNTiyxDQepyCA5rZXgxCK4DZqqKgI
  on:
    tags: true

